server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:55001/ead-course
    username: postgres
    password: postgrespw
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true


